unixdiff canon_abbrevs.h ..\SwordHeaderFilesOld\canon_abbrevs.h > _canon_abbrevs.txt
unixdiff canon_calvin.h ..\SwordHeaderFilesOld\canon_calvin.h > _canon_calvin.txt
unixdiff canon_catholic2.h ..\SwordHeaderFilesOld\canon_catholic2.h > _canon_catholic2.txt
unixdiff canon_catholic.h ..\SwordHeaderFilesOld\canon_catholic.h > _canon_catholic.txt
unixdiff canon_darbyfr.h ..\SwordHeaderFilesOld\canon_darbyfr.h > _canon_darbyfr.txt
unixdiff canon_german.h ..\SwordHeaderFilesOld\canon_german.h > _canon_german.txt
unixdiff canon.h ..\SwordHeaderFilesOld\canon.h > _canon.txt
unixdiff canon_kjva.h ..\SwordHeaderFilesOld\canon_kjva.h > _canon_kjva.txt
unixdiff canon_leningrad.h ..\SwordHeaderFilesOld\canon_leningrad.h > _canon_leningrad.txt
unixdiff canon_luther.h ..\SwordHeaderFilesOld\canon_luther.h > _canon_luther.txt
unixdiff canon_lxx.h ..\SwordHeaderFilesOld\canon_lxx.h > _canon_lxx.txt
unixdiff canon_mt.h ..\SwordHeaderFilesOld\canon_mt.h > _canon_mt.txt
unixdiff canon_nrsva.h ..\SwordHeaderFilesOld\canon_nrsva.h > _canon_nrsva.txt
unixdiff canon_nrsv.h ..\SwordHeaderFilesOld\canon_nrsv.h > _canon_nrsv.txt
unixdiff canon_null.h ..\SwordHeaderFilesOld\canon_null.h > _canon_null.txt
unixdiff canon_orthodox.h ..\SwordHeaderFilesOld\canon_orthodox.h > _canon_orthodox.txt
unixdiff canon_segond.h ..\SwordHeaderFilesOld\canon_segond.h > _canon_segond.txt
unixdiff canon_synodal.h ..\SwordHeaderFilesOld\canon_synodal.h > _canon_synodal.txt
unixdiff canon_synodalprot.h ..\SwordHeaderFilesOld\canon_synodalprot.h > _canon_synodalprot.txt
unixdiff canon_vulg.h ..\SwordHeaderFilesOld\canon_vulg.h > _canon_vulg.txt
